# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-06 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_contactus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='name',
            field=models.CharField(default='blank', max_length=254),
        ),
    ]
