# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-10 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='mobile_number',
            field=models.CharField(max_length=12),
        ),
    ]
