# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-21 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0013_ngotemp'),
        ('users', '0005_auto_20170311_0200'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='project',
            field=models.ForeignKey(default=2333, on_delete=models.SET('project not set'), to='data.Project'),
        ),
    ]
