# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-21 21:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20170322_0232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_details',
            name='pincode',
        ),
    ]
