# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-21 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_user_details_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='pincode',
            field=models.CharField(default='', max_length=20),
        ),
    ]
