# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-21 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_user_details_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='pincode',
            field=models.IntegerField(),
        ),
    ]
