# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-22 19:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0013_auto_20170322_0257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='donor_id',
        ),
        migrations.AddField(
            model_name='donation',
            name='donor',
            field=models.ForeignKey(on_delete=models.SET('team member not set'), to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
