# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-31 04:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0018_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.IntegerField(blank=True)),
                ('card_holder', models.CharField(blank=True, max_length=40)),
                ('expiration_date', models.DateField(blank=True)),
                ('cvv', models.IntegerField(blank=True)),
                ('username', models.ForeignKey(on_delete=models.SET('team member not set'), to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
