# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-31 04:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_card_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card_details',
            name='card_number',
            field=models.IntegerField(),
        ),
    ]
