# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-31 04:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20170331_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card_details',
            name='card_holder',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
