# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-31 04:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_auto_20170331_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card_details',
            name='expiration_date',
            field=models.CharField(max_length=40),
        ),
    ]
