# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-16 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_causes_i_care_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
