# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-16 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_auto_20170416_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='donation',
            name='transaction_id',
            field=models.CharField(default='not set', max_length=150),
        ),
    ]
