# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-16 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_auto_20170416_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='id',
        ),
        migrations.AlterField(
            model_name='donation',
            name='transaction_id',
            field=models.CharField(default='not set', max_length=150, primary_key=True, serialize=False),
        ),
    ]
