# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-16 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_auto_20170416_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='name',
            field=models.CharField(default='not set', max_length=150),
        ),
    ]
