# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-16 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_donation_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='causes_i_care_about',
            name='id',
        ),
        migrations.AddField(
            model_name='causes_i_care_about',
            name='primary_key',
            field=models.CharField(default='not set', max_length=150, primary_key=True, serialize=False),
        ),
    ]
