# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-04 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20170219_0336'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='banner',
            field=models.ImageField(blank=True, upload_to=b''),
        ),
        migrations.AddField(
            model_name='project',
            name='story',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to=b''),
        ),
    ]
