# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-04 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20170304_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_page_desc',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='project',
            name='project_page_title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
