# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-05 06:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_remove_project_project_page_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='rating',
            field=models.IntegerField(choices=[('One', 1), ('Two', 2), ('Third', 3), ('Fourth', 4), ('Five', 5)], default=1),
        ),
    ]
