# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-05 07:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_auto_20170305_1231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='rating',
        ),
    ]
