# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-15 06:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_auto_20170306_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='gallery1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='gallery2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='gallery3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='gallery4',
            field=models.TextField(blank=True),
        ),
    ]
