# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-20 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0012_givemonthly_giveonce'),
    ]

    operations = [
        migrations.CreateModel(
            name='NGOtemp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sector', models.CharField(max_length=200)),
                ('since', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('legal_id', models.CharField(max_length=200)),
                ('affiliation', models.CharField(max_length=200)),
                ('board_no', models.CharField(max_length=200)),
                ('employee_no', models.CharField(max_length=200)),
                ('min_pay', models.CharField(max_length=200)),
                ('avg_pay', models.CharField(max_length=200)),
                ('offices_no', models.CharField(max_length=200)),
                ('office_loc', models.CharField(max_length=200)),
            ],
        ),
    ]
