# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-21 15:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0014_timelineevent'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TimelineEvent',
            new_name='TimelineEvents',
        ),
    ]
