# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-21 16:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0016_timelineevents_days_span'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timelineevents',
            name='project_id',
        ),
        migrations.DeleteModel(
            name='TimelineEvents',
        ),
    ]
