# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-21 17:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0021_remove_timelineevent_project_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TimelineEvent',
        ),
    ]
