# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-22 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0024_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryPic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.TextField()),
                ('desc', models.TextField(blank=True)),
                ('link', models.TextField()),
                ('project_id', models.ForeignKey(on_delete=models.SET('project not set'), to='data.Project')),
            ],
        ),
    ]
